/* Example driver program for sbox. */
/* Automatically generated by SBV. Edit as you see fit! */

#include <inttypes.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <stdio.h>
#include "sbox.h"

int main(void)
{
  const SWord8 __result = sbox(231);

  printf("sbox(231) = %"PRIu8"\n", __result);

  return 0;
}
